version: "3.8"

services:
  opencv_app:
    build: .
    image: meu-opencv-app
    container_name: opencv_app
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    stdin_open: true
    tty: true
